<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sap_lfa1', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text('MANDT')->nullable();
            $table->text('LIFNR')->nullable();
            $table->text('LAND1')->nullable();
            $table->text('NAME1')->nullable();
            $table->text('NAME2')->nullable();
            $table->text('NAME3')->nullable();
            $table->text('NAME4')->nullable();
            $table->text('ORT01')->nullable();
            $table->text('ORT02')->nullable();
            $table->text('PFACH')->nullable();
            $table->text('PSTL2')->nullable();
            $table->text('PSTLZ')->nullable();
            $table->text('REGIO')->nullable();
            $table->text('SORTL')->nullable();
            $table->text('STRAS')->nullable();
            $table->text('ADRNR')->nullable();
            $table->text('MCOD1')->nullable();
            $table->text('MCOD2')->nullable();
            $table->text('MCOD3')->nullable();
            $table->text('ANRED')->nullable();
            $table->text('BAHNS')->nullable();
            $table->text('BBBNR')->nullable();
            $table->text('BBSNR')->nullable();
            $table->text('BEGRU')->nullable();
            $table->text('BRSCH')->nullable();
            $table->text('BUBKZ')->nullable();
            $table->text('DATLT')->nullable();
            $table->text('DTAMS')->nullable();
            $table->text('DTAWS')->nullable();
            $table->text('ERDAT')->nullable();
            $table->text('ERNAM')->nullable();
            $table->text('ESRNR')->nullable();
            $table->text('KONZS')->nullable();
            $table->text('KTOKK')->nullable();
            $table->text('KUNNR')->nullable();
            $table->text('LNRZA')->nullable();
            $table->text('LOEVM')->nullable();
            $table->text('SPERR')->nullable();
            $table->text('SPERM')->nullable();
            $table->text('SPRAS')->nullable();
            $table->text('STCD1')->nullable();
            $table->text('STCD2')->nullable();
            $table->text('STKZA')->nullable();
            $table->text('STKZU')->nullable();
            $table->text('TELBX')->nullable();
            $table->text('TELF1')->nullable();
            $table->text('TELF2')->nullable();
            $table->text('TELFX')->nullable();
            $table->text('TELTX')->nullable();
            $table->text('TELX1')->nullable();
            $table->text('XCPDK')->nullable();
            $table->text('XZEMP')->nullable();
            $table->text('VBUND')->nullable();
            $table->text('FISKN')->nullable();
            $table->text('STCEG')->nullable();
            $table->text('STKZN')->nullable();
            $table->text('SPERQ')->nullable();
            $table->text('GBORT')->nullable();
            $table->text('GBDAT')->nullable();
            $table->text('SEXKZ')->nullable();
            $table->text('KRAUS')->nullable();
            $table->text('REVDB')->nullable();
            $table->text('QSSYS')->nullable();
            $table->text('KTOCK')->nullable();
            $table->text('PFORT')->nullable();
            $table->text('WERKS')->nullable();
            $table->text('LTSNA')->nullable();
            $table->text('WERKR')->nullable();
            $table->text('PLKAL')->nullable();
            $table->text('DUEFL')->nullable();
            $table->text('TXJCD')->nullable();
            $table->text('SPERZ')->nullable();
            $table->text('SCACD')->nullable();
            $table->text('SFRGR')->nullable();
            $table->text('LZONE')->nullable();
            $table->text('XLFZA')->nullable();
            $table->text('DLGRP')->nullable();
            $table->text('FITYP')->nullable();
            $table->text('STCDT')->nullable();
            $table->text('REGSS')->nullable();
            $table->text('ACTSS')->nullable();
            $table->text('STCD3')->nullable();
            $table->text('STCD4')->nullable();
            $table->text('STCD5')->nullable();
            $table->text('IPISP')->nullable();
            $table->text('TAXBS')->nullable();
            $table->text('PROFS')->nullable();
            $table->text('STGDL')->nullable();
            $table->text('EMNFR')->nullable();
            $table->text('LFURL')->nullable();
            $table->text('J_1KFREPRE')->nullable();
            $table->text('J_1KFTBUS')->nullable();
            $table->text('J_1KFTIND')->nullable();
            $table->text('CONFS')->nullable();
            $table->text('UPDAT')->nullable();
            $table->text('UPTIM')->nullable();
            $table->text('NODEL')->nullable();
            $table->text('QSSYSDAT')->nullable();
            $table->text('PODKZB')->nullable();
            $table->text('FISKU')->nullable();
            $table->text('STENR')->nullable();
            $table->text('CARRIER_CONF')->nullable();
            $table->text('MIN_COMP')->nullable();
            $table->text('TERM_LI')->nullable();
            $table->text('CRC_NUM')->nullable();
            $table->text('J_SC_CAPITAL')->nullable();
            $table->text('J_SC_CURRENCY')->nullable();
            $table->text('ALC')->nullable();
            $table->text('PMT_OFFICE')->nullable();
            $table->text('PSOFG')->nullable();
            $table->text('PSOIS')->nullable();
            $table->text('PSON1')->nullable();
            $table->text('PSON2')->nullable();
            $table->text('PSON3')->nullable();
            $table->text('PSOVN')->nullable();
            $table->text('PSOTL')->nullable();
            $table->text('PSOHS')->nullable();
            $table->text('PSOST')->nullable();
            $table->text('TRANSPORT_CHAIN')->nullable();
            $table->text('STAGING_TIME')->nullable();
            $table->text('SCHEDULING_TYPE')->nullable();
            $table->text('SUBMI_RELEVANT')->nullable();
            $table->timestamp('created_at')->useCurrent()->index();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sap_lfa1');
    }
};
