<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sap_mseg', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text('MANDT')->nullable();
            $table->text('MBLNR')->nullable();
            $table->text('MJAHR')->nullable();
            $table->text('ZEILE')->nullable();
            $table->text('LINE_ID')->nullable();
            $table->text('PARENT_ID')->nullable();
            $table->text('LINE_DEPTH')->nullable();
            $table->text('MAA_URZEI')->nullable();
            $table->text('BWART')->nullable();
            $table->text('XAUTO')->nullable();
            $table->text('MATNR')->nullable();
            $table->text('WERKS')->nullable();
            $table->text('LGORT')->nullable();
            $table->text('CHARG')->nullable();
            $table->text('INSMK')->nullable();
            $table->text('ZUSCH')->nullable();
            $table->text('ZUSTD')->nullable();
            $table->text('SOBKZ')->nullable();
            $table->text('LIFNR')->nullable();
            $table->text('KUNNR')->nullable();
            $table->text('KDAUF')->nullable();
            $table->text('KDPOS')->nullable();
            $table->text('KDEIN')->nullable();
            $table->text('PLPLA')->nullable();
            $table->text('SHKZG')->nullable();
            $table->text('WAERS')->nullable();
            $table->text('DMBTR')->nullable();
            $table->text('BNBTR')->nullable();
            $table->text('BUALT')->nullable();
            $table->text('SHKUM')->nullable();
            $table->text('DMBUM')->nullable();
            $table->text('BWTAR')->nullable();
            $table->text('MENGE')->nullable();
            $table->text('MEINS')->nullable();
            $table->text('ERFMG')->nullable();
            $table->text('ERFME')->nullable();
            $table->text('BPMNG')->nullable();
            $table->text('BPRME')->nullable();
            $table->text('EBELN')->nullable();
            $table->text('EBELP')->nullable();
            $table->text('LFBJA')->nullable();
            $table->text('LFBNR')->nullable();
            $table->text('LFPOS')->nullable();
            $table->text('SJAHR')->nullable();
            $table->text('SMBLN')->nullable();
            $table->text('SMBLP')->nullable();
            $table->text('ELIKZ')->nullable();
            $table->text('SGTXT')->nullable();
            $table->text('EQUNR')->nullable();
            $table->text('WEMPF')->nullable();
            $table->text('ABLAD')->nullable();
            $table->text('GSBER')->nullable();
            $table->text('KOKRS')->nullable();
            $table->text('PARGB')->nullable();
            $table->text('PARBU')->nullable();
            $table->text('KOSTL')->nullable();
            $table->text('PROJN')->nullable();
            $table->text('AUFNR')->nullable();
            $table->text('ANLN1')->nullable();
            $table->text('ANLN2')->nullable();
            $table->text('XSKST')->nullable();
            $table->text('XSAUF')->nullable();
            $table->text('XSPRO')->nullable();
            $table->text('XSERG')->nullable();
            $table->text('GJAHR')->nullable();
            $table->text('XRUEM')->nullable();
            $table->text('XRUEJ')->nullable();
            $table->text('BUKRS')->nullable();
            $table->text('BELNR')->nullable();
            $table->text('BUZEI')->nullable();
            $table->text('BELUM')->nullable();
            $table->text('BUZUM')->nullable();
            $table->text('RSNUM')->nullable();
            $table->text('RSPOS')->nullable();
            $table->text('KZEAR')->nullable();
            $table->text('PBAMG')->nullable();
            $table->text('KZSTR')->nullable();
            $table->text('UMMAT')->nullable();
            $table->text('UMWRK')->nullable();
            $table->text('UMLGO')->nullable();
            $table->text('UMCHA')->nullable();
            $table->text('UMZST')->nullable();
            $table->text('UMZUS')->nullable();
            $table->text('UMBAR')->nullable();
            $table->text('UMSOK')->nullable();
            $table->text('KZBEW')->nullable();
            $table->text('KZVBR')->nullable();
            $table->text('KZZUG')->nullable();
            $table->text('WEUNB')->nullable();
            $table->text('PALAN')->nullable();
            $table->text('LGNUM')->nullable();
            $table->text('LGTYP')->nullable();
            $table->text('LGPLA')->nullable();
            $table->text('BESTQ')->nullable();
            $table->text('BWLVS')->nullable();
            $table->text('TBNUM')->nullable();
            $table->text('TBPOS')->nullable();
            $table->text('XBLVS')->nullable();
            $table->text('VSCHN')->nullable();
            $table->text('NSCHN')->nullable();
            $table->text('DYPLA')->nullable();
            $table->text('UBNUM')->nullable();
            $table->text('TBPRI')->nullable();
            $table->text('TANUM')->nullable();
            $table->text('WEANZ')->nullable();
            $table->text('GRUND')->nullable();
            $table->text('EVERS')->nullable();
            $table->text('EVERE')->nullable();
            $table->text('IMKEY')->nullable();
            $table->text('KSTRG')->nullable();
            $table->text('PAOBJNR')->nullable();
            $table->text('PRCTR')->nullable();
            $table->text('PS_PSP_PNR')->nullable();
            $table->text('NPLNR')->nullable();
            $table->text('AUFPL')->nullable();
            $table->text('APLZL')->nullable();
            $table->text('AUFPS')->nullable();
            $table->text('VPTNR')->nullable();
            $table->text('FIPOS')->nullable();
            $table->text('SAKTO')->nullable();
            $table->text('BSTMG')->nullable();
            $table->text('BSTME')->nullable();
            $table->text('XWSBR')->nullable();
            $table->text('EMLIF')->nullable();
            $table->text('EXBWR')->nullable();
            $table->text('VKWRT')->nullable();
            $table->text('AKTNR')->nullable();
            $table->text('ZEKKN')->nullable();
            $table->text('VFDAT')->nullable();
            $table->text('CUOBJ_CH')->nullable();
            $table->text('EXVKW')->nullable();
            $table->text('PPRCTR')->nullable();
            $table->text('RSART')->nullable();
            $table->text('GEBER')->nullable();
            $table->text('FISTL')->nullable();
            $table->text('MATBF')->nullable();
            $table->text('UMMAB')->nullable();
            $table->text('BUSTM')->nullable();
            $table->text('BUSTW')->nullable();
            $table->text('MENGU')->nullable();
            $table->text('WERTU')->nullable();
            $table->text('LBKUM')->nullable();
            $table->text('SALK3')->nullable();
            $table->text('VPRSV')->nullable();
            $table->text('FKBER')->nullable();
            $table->text('DABRBZ')->nullable();
            $table->text('VKWRA')->nullable();
            $table->text('DABRZ')->nullable();
            $table->text('XBEAU')->nullable();
            $table->text('LSMNG')->nullable();
            $table->text('LSMEH')->nullable();
            $table->text('KZBWS')->nullable();
            $table->text('QINSPST')->nullable();
            $table->text('URZEI')->nullable();
            $table->text('J_1BEXBASE')->nullable();
            $table->text('MWSKZ')->nullable();
            $table->text('TXJCD')->nullable();
            $table->text('EMATN')->nullable();
            $table->text('J_1AGIRUPD')->nullable();
            $table->text('VKMWS')->nullable();
            $table->text('HSDAT')->nullable();
            $table->text('BERKZ')->nullable();
            $table->text('MAT_KDAUF')->nullable();
            $table->text('MAT_KDPOS')->nullable();
            $table->text('MAT_PSPNR')->nullable();
            $table->text('XWOFF')->nullable();
            $table->text('BEMOT')->nullable();
            $table->text('PRZNR')->nullable();
            $table->text('LLIEF')->nullable();
            $table->text('LSTAR')->nullable();
            $table->text('XOBEW')->nullable();
            $table->text('GRANT_NBR')->nullable();
            $table->text('ZUSTD_T156M')->nullable();
            $table->text('SPE_GTS_STOCK_TY')->nullable();
            $table->text('KBLNR')->nullable();
            $table->text('KBLPOS')->nullable();
            $table->text('XMACC')->nullable();
            $table->text('VGART_MKPF')->nullable();
            $table->text('BUDAT_MKPF')->nullable();
            $table->text('CPUDT_MKPF')->nullable();
            $table->text('CPUTM_MKPF')->nullable();
            $table->text('USNAM_MKPF')->nullable();
            $table->text('XBLNR_MKPF')->nullable();
            $table->text('TCODE2_MKPF')->nullable();
            $table->text('VBELN_IM')->nullable();
            $table->text('VBELP_IM')->nullable();
            $table->text('BEV2ED_KZ_VER')->nullable();
            $table->text('BEV2ED_USER')->nullable();
            $table->text('BEV2ED_AEDAT')->nullable();
            $table->text('BEV2ED_AETIM')->nullable();
            $table->text('DISUB_OWNER')->nullable();
            $table->text('OINAVNW')->nullable();
            $table->text('OICONDCOD')->nullable();
            $table->text('CONDI')->nullable();
            $table->timestamp('created_at')->useCurrent()->index();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sap_mseg');
    }
};
